apiVersion: v1
kind: Pod
metadata:
  name: bert-race-ft
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: "nvcr.io/nvidia/pytorch:23.05-py3"
      workingDir: "/megatron"
      command: ["sh", "examples/finetune_race_distributed.sh"]
      resources:
        limits:
          nvidia.com/gpu: 4
      volumeMounts:
        - mountPath: /megatron
          name: main
  volumes:
    - name: main
      hostPath:
        path: /home/abdelrahman/MBZUAI/Megatron-LM/
